# Generated by Django 5.1 on 2024-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkUp', '0004_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
